In [5]:
try:
    if 5/0:
        print('5/0 successfully executed')
    else:
        print('5/0 is not successfully executed')
except Exception as e:
    print('Error, so captured in except ', e)

Error, so captured in except  division by zero


In [23]:
subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]  

for i in [z+' '+x+' '+y+'.' for z in subjects for x in verbs for y in objects]:
    print (i)
    

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [20]:
import numpy as np
X = [1,2,3,4,5]
Y = np.array([1, 2, 3, 4,5])
n = 5

V = np.vander(X, increasing=False)
R = np.column_stack([pow(Y,(n-1-i)) for i in range(n)])

print(type(V))
print (V)
print(type(R))
print (R)

<class 'numpy.ndarray'>
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
<class 'numpy.ndarray'>
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
